[module/date]
type = internal/date

interval = 1.0

time = %I:%M %P
format-foreground = ${color.fg}
date-alt = " %a, %d %b %y"

format = <label>
format-prefix = "🕘"

label = %date% %time%

######################################################

[module/network]
type = internal/network
interface-type = wired

interval = 3.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-prefix = "📡"

speed-unit = ""
label-connected = "%netspeed%"
label-connected-foreground = ${color.fg}

format-disconnected = <label-disconnected>
format-disconnected-prefix = 📡

label-disconnected = Offline
label-disconnected-foreground = ${color.red}

######################################################

[module/pulseaudio]
type = internal/pulseaudio

sink = alsa_output.pci-0000_00_1b.0.analog-stereo
use-ui-max = true
interval = 5

format-volume = <ramp-volume><label-volume>
format-volume-prefix = ""

label-volume = " %percentage% "
label-volume-foreground = ${color.fg}

format-muted = <label-muted>
format-muted-prefix = 🔇
label-muted = "Muted"
label-muted-foreground = ${color.red}

ramp-volume-0 = 🔇
ramp-volume-1 = 🔈
ramp-volume-2 = 🔉
ramp-volume-3 = 🔊
ramp-volume-4 = 🔊

click-right = pavucontrol

######################################################

[module/title]
type = internal/xwindow

format = <label>

label = "%title%"
label-font = 2
label-maxlen = 25

label-empty = "Arch Linux"
label-empty-font = 2


######################################################

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true
occupied-scroll = false


format = <label-state>
format-font = 1

label-focused =  
label-focused-padding = 1
label-focused-foreground = ${color.blue}

label-occupied = ●
label-occupied-padding = 1
label-occupied-foreground= ${color.pink}

label-urgent = %icon%
label-urgent-padding = 1

label-empty =  ﯇
label-empty-foreground = ${color.fg}
label-empty-padding = 1

######################################################

[module/updates]
type = custom/script
exec = ~/.config/bspwm/scripts/updates.sh
interval = 60
label = " %output%"
click-left = termite --hold -t updating -e "yay -Syyuu --devel"
click-right = termite --hold -t updating -e "checkupdates"
format-prefix = "📦"

######################################################

[module/launcher]
type = custom/text

content = 󰣇
content-foreground = ${color.blue-arch}
content-font = 3

click-left = rofi -no-lazy-grab -show drun -theme $HOME/.config/bspwm/rices/$RICETHEME/launcher.rasi
click-right = $HOME/.config/bspwm/scripts/RiceSelector &

######################################################

[module/sep]
type = custom/text
content = " "

######################################################

[module/dots]
type = custom/text
content = " "
content-foreground = ${color.green}

######################################################

[module/spotify]
type = custom/script
interval = 1
format-prefix = " "
format = <label>
exec = python ~/.config/1.py -f '{artist}: {song}'
; format-underline = #1db954
;control players (optional)
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous 