#!/usr/bin/env bash

read -r RICETHEME <"$HOME"/.config/bspwm/.rice
export RICETHEME
PATH="$HOME/.config/bspwm/scripts:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"
xinput disable 20 &
setxkbmap -layout "us,ru" -option "grp:caps_toggle"

source $HOME/.config/bspwm/scripts/Unsplash &

export _JAVA_AWT_WM_NONREPARENTING=1

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1-0"

setup_workspaces() {
  bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7
  bspc monitor "$EXTERNAL_MONITOR" -d 8 9 10
}

monitor_add() {
  for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | sed 8q); do
    bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
  done
  bspc desktop Desktop --remove
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
}

monitor_remove() {
  bspc monitor "$EXTERNAL_MONITOR" -a Desktop
  for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR"); do
    bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
  done
  bspc desktop Desktop --remove
  bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7
}

if xrandr --query | grep -q "${EXTERNAL_MONITOR} connected"; then
  xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --mode 1920x1080 --pos 1920x0 --rotate normal --right-of "$INTERNAL_MONITOR"
  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 3 ]]; then
    monitor_add
  fi
  bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
  xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --off
  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 7 ]]; then
    monitor_remove
  fi
fi

setup_workspaces

#  ┌┐ ┌─┐┌─┐┬ ┬┌┬┐  ┌─┐┌─┐┌┐┌┌─┐┬┌─┐
#  ├┴┐└─┐├─┘││││││  │  │ ││││├┤ ││ ┬
#  └─┘└─┘┴  └┴┘┴ ┴  └─┘└─┘┘└┘└  ┴└─┘

bspc config external_rules_command $HOME/.config/bspwm/scripts/ExternalRules

bspc config split_ratio 0.52
bspc config single_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config border_radius       10
bspc config borderless_monocle   false

bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on

#  ┬  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬  ┌─┐┌─┐─┐ ┬┬ ┬  ┬─┐┬┌─┐┌─┐┌─┐
#  │  ├─┤│ │││││  ├─┤  └─┐├┤ ┌┴┬┘└┬┘  ├┬┘││  ├┤ └─┐
#  ┴─┘┴ ┴└─┘┘└┘└─┘┴ ┴  └─┘└─┘┴ └─ ┴   ┴└─┴└─┘└─┘└─┘

# Set system vars for polybar
. SetSysVars

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "eww" "sxhkd" "dunst")

for process in "${processes[@]}"; do
	if pidof -q "$process"; then
		pkill -9 -x "$process" >/dev/null
		sleep 0.1
	fi
done

# Load colors, dunst, bars and/or eww widgets
. ${rice_dir}/Theme.sh

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
picom --config "$HOME"/.config/bspwm/picom.conf &
#picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf &

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill ${rice_dir}/walls

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Reload .Xresources
xrdb -load ~/.Xresources

# Fix cursor
xsetroot -cursor_name crosshair
