#! /bin/sh

export RICETHEME=$(<$HOME/.config/bspwm/rice.cfg)
PATH="$HOME/.config/bspwm/scripts:$PATH"
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"
xinput --disable 20
$HOME/display.sh

########### Workspaces

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7'
		let name++
	done
}

workspaces

########### Launch The Rice!!

source LaunchWorld
SetGirlFriendRice
AutoStartApps

########### bspwm conf

bspc config external_rules_command ~/.config/bspwm/scripts/external_rules
bspc config window_gap 8

bspc config single_monocle true
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config pointer_motion_interval 16
