#!/usr/bin/env bash
#  ┬┌┬┐┌─┐┌─┐┬─┐┌┬┐┌─┐┌┐┌┌┬┐  ┬  ┬┌─┐┬─┐┬┌─┐┌┐ ┬  ┌─┐┌─┐
#  ││││├─┘│ │├┬┘ │ ├─┤│││ │   └┐┌┘├─┤├┬┘│├─┤├┴┐│  ├┤ └─┐
#  ┴┴ ┴┴  └─┘┴└─ ┴ ┴ ┴┘└┘ ┴    └┘ ┴ ┴┴└─┴┴ ┴└─┘┴─┘└─┘└─┘

read -r RICETHEME <"$HOME"/.config/bspwm/.rice
export RICETHEME
export TERMINAL=kitty
PATH="$HOME/.config/bspwm/scripts:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1-0"
STATUS=$(xrandr -q | grep $EXTERNAL_MONITOR)

# Disablee touchpad
xinput disable 20 &

# Set sys lang switcher
setxkbmap -layout "us,ru" -option "grp:caps_toggle"

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

if [[ ! $STATUS == *disconnected* ]]; then
	xrandr --output $INTERNAL_MONITOR --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1-0 --off --output DP-1-1 --off --output $EXTERNAL_MONITOR --mode 1920x1080 --pos 1920x0 --rotate normal
fi

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6' '7'
		#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
		((name++))
	done
}

workspaces

bspc config external_rules_command $HOME/.config/bspwm/scripts/ExternalRules
bspc config split_ratio 0.50
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config border_radius 10
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#  ┬  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬  ┌─┐┌─┐─┐ ┬┬ ┬  ┬─┐┬┌─┐┌─┐┌─┐
#  │  ├─┤│ │││││  ├─┤  └─┐├┤ ┌┴┬┘└┬┘  ├┬┘││  ├┤ └─┐
#  ┴─┘┴ ┴└─┘┘└┘└─┘┴ ┴  └─┘└─┘┴ └─ ┴   ┴└─┴└─┘└─┘└─┘

# Set system vars for polybar
. SetSysVars

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "eww" "sxhkd" "dunst")

for process in "${processes[@]}"; do
	if pidof -q "$process"; then
		pkill -9 -x "$process" >/dev/null
		sleep 0.1
	fi
done

# Load colors, dunst, bars and/or eww widgets
. ${rice_dir}/Theme.sh

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
picom --config "$HOME"/.config/bspwm/picom.conf &
#picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf &

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill ${rice_dir}/walls

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr
