#!/usr/bin/env bash

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

dir="$HOME/.config/bspwm"
rofi_command="rofi -theme $HOME/.config/bspwm/scripts/RiceSelector.rasi"

# Options
emilia="󰔿 Emilia"
jan="󰔿 Jan"
aline="󰔿 Aline"
isabel="󰔿 Isabel"
andrea="󰔿 Andrea"
cynthia="󰔿 Cynthia"
silvia="󰔿 Silvia"
melissa="󰔿 Melissa"
pamela="󰔿 Pamela"
cristina="󰔿 Cristina"
karla="󰔿 Karla"
z0mbi3="󰔿 z0mbi3"

options="$emilia\n$jan\n$aline\n$isabel\n$andrea\n$cynthia\n$silvia\n$melissa\n$pamela\n$cristina\n$karla\n$z0mbi3"
chosen="$(printf "$options" | $rofi_command -dmenu)"
case $chosen in

$emilia)
	cat <<<"emilia" >$dir/rice.cfg
	bspc wm -r
	;;
$jan)
	cat <<<"jan" >$dir/rice.cfg
	bspc wm -r
	;;
$aline)
	cat <<<"aline" >$dir/rice.cfg
	bspc wm -r
	;;
$isabel)
	cat <<<"isabel" >$dir/rice.cfg
	bspc wm -r
	;;
$andrea)
	cat <<<"andrea" >$dir/rice.cfg
	bspc wm -r
	;;
$cynthia)
	cat <<<"cynthia" >$dir/rice.cfg
	bspc wm -r
	;;
$silvia)
	cat <<<"silvia" >$dir/rice.cfg
	bspc wm -r
	;;
$melissa)
	cat <<<"melissa" >$dir/rice.cfg
	bspc wm -r
	;;
$pamela)
	cat <<<"pamela" >$dir/rice.cfg
	bspc wm -r
	;;
$cristina)
	cat <<<"cristina" >$dir/rice.cfg
	bspc wm -r
	;;
$karla)
	cat <<<"karla" >$dir/rice.cfg
	bspc wm -r
	;;
$z0mbi3)
	cat <<<"z0mbi3" >$dir/rice.cfg
	bspc wm -r
	;;
esac
