#!/usr/bin/env bash

img_dir=~/Pictures/wallpapers
resolution="1920x1080"
image_url="https://source.unsplash.com/featured/${resolution}/?tokyo,night,dark"
current_time=$(date +"%Y-%m-%d_%H-%M-%S")

if [ ! -d "$img_dir" ]; then
    mkdir $img_dir
fi

if [ "$(ls -A $img_dir)" ]; then
    find $img_dir -type f -mtime +1 -delete
fi

wget -q "$image_url" -O $img_dir/$current_time.jpg

if [ -f $img_dir/$current_time.jpg ]; then
    feh --bg-scale $img_dir/$current_time.jpg
    echo "Changed wallpaper image successfully!"
else
    echo "Error: Image not downloaded!"
    exit 1
fi
